name: 'Build amc2moodle multi-arch containers'

on:
  workflow_run:
    workflows: ["Publish Python 🐍 distribution 📦 to PyPI and create a github release"]
    types: [completed]
  # push:
    # branches:
    #   - 'master'
    # tags:
    #   - 'v*'


jobs:
  build-multi-arch:
    name: 'Build amc2moodle multi-arch containers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@main
        with:
          latest-branches: 'main,master'
      - name: "Build:checkout"
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to Github Packages
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: 'Build:dockerimage'
        id: docker_build
        uses: docker/build-push-action@master
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./docker
          platforms: linux/amd64,linux/arm64 #, linux/arm/v7
          tags: ghcr.io/${{ github.repository_owner }}/amc2moodle:${{ steps.docker-tag.outputs.tag }},ghcr.io/${{ github.repository_owner }}/amc2moodle:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha
          # # build on feature branches, push only on main branch
          # push: ${{ github.ref == 'refs/heads/main' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
