# This is a basic workflow to help you get started with Actions

name: CI-mac-os

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.5]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install the dependences
      run: |
        python -m pip install --upgrade pip
        
        # install brew package
        brew cask install basictex        
        brew install libxml2
        brew install libxslt
        brew install imagemagick
        
        brew install cpanm
        #brew update
        export PATH="/usr/local/opt/libxml2/bin:$PATH"
        export PATH="/usr/local/opt/libxslt/bin:$PATH"
        cpanm --configure-args="INC=\"$(xml2-config --cflags) $(xslt-config --cflags)\" LIBS=\"$(xml2-config --libs) $(xslt-config --libs) -lexslt\"" XML::LibXSLT
        cpanm Archive::Zip DB_File File::Which Getopt::Long Image::Size IO::String JSON::XS LWP MIME::Base64 Parse::RecDescent Pod::Parser Text::Unidecode Test::More URI XML::LibXML UUID::Tiny # XML::LibXSLT
        brew install latexml 

        
    - name: Test latexml alone
      run: |
        latexml --noparse --nocomment --path=./src --dest=./out.xml  ./test/QCM.tex

        

    

