# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install the dependences
      run: |
        python -m pip install --upgrade pip
        
        # install ubuntu package
        sudo apt-get install python-pythonmagick
        # add libtext-unidecode-perl to fix bug in deb package : https://github.com/brucemiller/LaTeXML/issues/1022
        sudo apt get install libtext-unidecode-perl
        sudo apt-get install latexml
        sudo apt-get install xmlindent
        
        # install python package
        pip install lxml
        # pip install pillow
        # pip install pdf2image
        
    - name: Test latexml
      run: |
        latexml --noparse --nocomment --path=./src --dest=./out.xml  ./src/QCM.tex
        
        

    
